version: '3'

networks:
  target_network:
    external:
      name: ${environmentName}

services:
  # Databases and Caches
  postgresql:
    container_name: ${environmentName}-${postgresqlContainerName}
    hostname: "${environmentName}-${postgresqlContainerName}"
    ports: 
      - ${environmentPortPrefix}000:5432
    environment: 
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ${postgresqlContainerVolumeDataPath}/:/var/lib/postgresql/data
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.0.2
    image: "postgres"
  mongodb:
    container_name: ${environmentName}-${mongodbContainerName}
    hostname: "${environmentName}-${mongodbContainerName}"
    ports: 
      - ${environmentPortPrefix}001:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
      - ${mongodbContainerVolumeDataPath}:/data/db
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.0.3
    image: "mongo"
  ravendb:
    container_name: ${environmentName}-${ravendbContainerName}
    hostname: "${environmentName}-${ravendbContainerName}"
    ports: 
      - ${environmentPortPrefix}002:38888
      - ${environmentPortPrefix}503:8080
    volumes:
      - ${ravendbContainerVolumeConfigPath}:/opt/RavenDB/config
      - ${ravendbContainerVolumeDataPath}:/opt/RavenDB/Server/RavenData
    environment: 
      RAVEN_Setup_Mode: "None"
      RAVEN_License_Eula_Accepted: "true"
      RAVEN_Security_UnsecuredAccessAllowed: "PrivateNetwork"
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.0.4
    image: "ravendb/ravendb"
  prometheus:
    container_name: ${environmentName}-${prometheusContainerName}
    hostname: "${environmentName}-${prometheusContainerName}"
    ports: 
      - ${environmentPortPrefix}504:9090
    volumes:
      - ${prometheusContainerVolumeConfigPath}:/prometheus
      - ${prometheusContainerVolumeDataPath}:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.0.5
    image: "prom/prometheus"
  # Queues
  rabbitmq:
    container_name: ${environmentName}-${rabbitmqContainerName}
    hostname: "${environmentName}-${rabbitmqContainerName}"
    ports: 
      - ${environmentPortPrefix}100:5672
      - ${environmentPortPrefix}506:15672
    volumes:
      - ${rabbitmqContainerVolumeDataPath}:/var/lib/rabbitmq
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.2.2
    image: "rabbitmq:3.8.5-management"
  # Other Apps
  pgadmin4:
    container_name: ${environmentName}-${pgadminContainerName}
    hostname: "${environmentName}-${pgadminContainerName}"
    ports: 
      - ${environmentPortPrefix}500:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.10.2
    image: "dpage/pgadmin4"
  mongoclient:
    container_name: ${environmentName}-${mongoclientContainerName}
    hostname: "${environmentName}-${mongoclientContainerName}"
    ports: 
      - ${environmentPortPrefix}502:3000
    volumes:
      - ${mongoclientContainerVolumeDataPath}:/data/db
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.10.3
    image: "mongoclient/mongoclient"
  grafana:
    container_name: ${environmentName}-${grafanaContainerName}
    hostname: "${environmentName}-${grafanaContainerName}"
    ports: 
      - ${environmentPortPrefix}505:3000
    volumes:
      - ${grafanaContainerVolumeDataPath}:/var/lib/grafana
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.10.4
    image: "grafana/grafana"
  sonarqube:
    container_name: ${environmentName}-${sonarqubeContainerName}
    hostname: "${environmentName}-${sonarqubeContainerName}"
    ports: 
      - ${environmentPortPrefix}507:9000
    volumes:
      - ${sonarqubeContainerVolumeDataPath}:/opt/sonarqube/data
      - ${sonarqubeContainerVolumeLogPath}:/opt/sonarqube/logs
      - ${sonarqubeContainerVolumeConfigPath}:/opt/sonarqube/conf
      - ${sonarqubeContainerVolumeExtensionPath}:/opt/sonarqube/extensions
    networks:
      target_network:
        ipv4_address: 172.${ipSecondOctect}.10.5
    image: "sonarqube:8.2-community"