version: '3'

networks:
  target_network:
    external:
      name: ${environment_name}

services:
  # Databases and Caches
  postgresql:
    container_name: ${environment_name}-postgres
    hostname: "${environment_name}-postgres"
    ports: 
      - ${environment_port_prefix}000:5432
    environment: 
      POSTGRES_PASSWORD: "postgres"
    networks:
      target_network:
        ipv4_address: 172.${ip_second_octect}.0.2
    image: "postgres"
  mongodb:
    container_name: ${environment_name}-mongo
    hostname: "${environment_name}-mongo"
    ports: 
      - ${environment_port_prefix}001:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    networks:
      target_network:
        ipv4_address: 172.${ip_second_octect}.0.3
    image: "mongo"
  # Other Apps
  pgadmin4:
    container_name: ${environment_name}-pgadmin4
    hostname: "${environment_name}-pgadmin4"
    ports: 
      - ${environment_port_prefix}500:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    networks:
      target_network:
        ipv4_address: 172.${ip_second_octect}.10.2
    image: "dpage/pgadmin4"